[project]
name = "time-statistic-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.126.0",
    "sqlmodel>=0.0.27",
    "uvicorn>=0.40.0",
]
